name: Deploy ASP.NET Core Web API to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ApplicationInsights__InstrumentationKey: ${{ secrets.APPLICATION_INSIGHTS_INSTRUMENTATION_KEY }}
      AzureBlobStorage__ConnectionString: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTIONSTRING }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish ./ImageService.API/ImageService.API.csproj -c Release -o publish

    - name: List publish folder contents
      run: ls -la publish
      
    - name: Build solution
      run: dotnet build ./ImageService.sln --configuration Release

    - name: Run unit tests
      run: dotnet test ./ImageService.sln --no-build --configuration Release --verbosity normal

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'axeleronimages'
        package: './publish'

    - name: Set Azure App Service environment variables
      uses: azure/CLI@v1
      with:
        azcliversion: 2.74.0
        inlineScript: |
          az webapp config appsettings set --resource-group MyResourceGroup --name axeleronimages --settings AzureBlobStorageConnectionString="${{ secrets.AZURE_BLOB_STORAGE_CONNECTIONSTRING }}" ApplicationInsightsInstrumentationKey="${{ secrets.APPLICATION_INSIGHTS_INSTRUMENTATION_KEY }}" SupportedImageExtensions="jpg,png,gif" MaxImageSizeInBytes="1073741824"
