name: Deploy ASP.NET Core Web API to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ApplicationInsights__InstrumentationKey: ${{ secrets.APPLICATION_INSIGHTS_INSTRUMENTATION_KEY }}
      AzureBlobStorage__ConnectionString: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: List publish folder contents
      run: ls -la publish

    - name: Run tests
      run: dotnet test ./ImageService.sln --no-build --configuration Release --verbosity normal

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'axeleronimages'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './publish'
